# file: postgresql/tasks/users.yml

- include: service_started.yml

- name: PostgreSQL | Make sure the PostgreSQL users are present
  postgresql_user:
    name: "{{item.name}}"
    password: "{{ item.pass | default(omit) }}"
    encrypted: "{{ item.encrypted | default(omit) }}"
    port: "{{postgresql_port}}"
    state: present
    login_user: "{{postgresql_admin_user}}"
  no_log: true
  become: yes
  become_user: "{{postgresql_admin_user}}"
  with_items: "{{postgresql_users}}"
  when: postgresql_users|length > 0
